# Generated by Django 3.2.8 on 2021-10-20 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20211018_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profilePic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
